github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: Preview Ready in GitPod

tasks:
  - name: Build Test
    init: yarn
    command: yarn build
  - name: Developer Preview
    init: yarn
    command: yarn dev